attention_head_size: 1
categorical_groups:
  special_days:
  - easter_day
  - good_friday
  - new_year
  - christmas
  - labor_day
  - independence_day
  - revolution_day_memorial
  - regional_games
  - fifa_u_17_world_cup
  - football_gold_cup
  - beer_capital
  - music_fest
dropout: 0.1
embedding_labels:
  agency:
    Agency_01: 0
    Agency_02: 1
    Agency_03: 2
    Agency_04: 3
    Agency_05: 4
    Agency_07: 5
    Agency_08: 6
    Agency_09: 7
    Agency_10: 8
    Agency_11: 9
    Agency_12: 10
    Agency_13: 11
    Agency_15: 12
    Agency_16: 13
    Agency_17: 14
    Agency_18: 15
    Agency_19: 16
    Agency_20: 17
    Agency_21: 18
    Agency_22: 19
    Agency_23: 20
    Agency_24: 21
    Agency_25: 22
    Agency_26: 23
    Agency_27: 24
    Agency_28: 25
    Agency_29: 26
    Agency_30: 27
    Agency_31: 28
    Agency_32: 29
    Agency_33: 30
    Agency_34: 31
    Agency_35: 32
    Agency_36: 33
    Agency_37: 34
    Agency_38: 35
    Agency_39: 36
    Agency_40: 37
    Agency_41: 38
    Agency_42: 39
    Agency_43: 40
    Agency_44: 41
    Agency_45: 42
    Agency_46: 43
    Agency_47: 44
    Agency_48: 45
    Agency_49: 46
    Agency_50: 47
    Agency_51: 48
    Agency_52: 49
    Agency_53: 50
    Agency_54: 51
    Agency_55: 52
    Agency_56: 53
    Agency_57: 54
    Agency_58: 55
    Agency_59: 56
    Agency_60: 57
  month:
    '1': 0
    '10': 1
    '11': 2
    '12': 3
    '2': 4
    '3': 5
    '4': 6
    '5': 7
    '6': 8
    '7': 9
    '8': 10
    '9': 11
  sku:
    SKU_01: 0
    SKU_02: 1
    SKU_03: 2
    SKU_04: 3
    SKU_05: 4
    SKU_06: 5
    SKU_07: 6
    SKU_08: 7
    SKU_11: 8
    SKU_12: 9
    SKU_14: 10
    SKU_15: 11
    SKU_17: 12
    SKU_18: 13
    SKU_20: 14
    SKU_21: 15
    SKU_22: 16
    SKU_23: 17
    SKU_24: 18
    SKU_26: 19
    SKU_27: 20
    SKU_28: 21
    SKU_31: 22
    SKU_32: 23
    SKU_34: 24
  special_days:
    '-': 0
    beer_capital: 1
    christmas: 2
    easter_day: 3
    good_friday: 4
    independence_day: 5
    labor_day: 6
    music_fest: 7
    new_year: 8
    regional_games: 9
    revolution_day_memorial: 10
embedding_paddings: []
embedding_sizes:
  agency:
  - 58
  - 16
  month:
  - 12
  - 6
  sku:
  - 25
  - 10
  special_days:
  - 11
  - 6
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: 10
logging_metrics: []
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: ranger
output_size: 7
reduce_on_plateau_patience: 4
share_single_variable_networks: false
static_categoricals:
- agency
- sku
static_reals:
- avg_population_2017
- avg_yearly_household_income_2017
- decoder_length
- volume_center
- volume_scale
time_varying_categoricals_decoder:
- special_days
- month
time_varying_categoricals_encoder:
- special_days
- month
time_varying_reals_decoder:
- time_idx
- price_regular
- discount_in_percent
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- price_regular
- discount_in_percent
- relative_time_idx
- volume
- log_volume
- industry_volume
- soda_volume
- avg_max_temp
- avg_volume_by_agency
- avg_volume_by_sku
weight_decay: 0.0
x_categoricals:
- agency
- sku
- easter_day
- good_friday
- new_year
- christmas
- labor_day
- independence_day
- revolution_day_memorial
- regional_games
- fifa_u_17_world_cup
- football_gold_cup
- beer_capital
- music_fest
- month
x_reals:
- avg_population_2017
- avg_yearly_household_income_2017
- decoder_length
- volume_center
- volume_scale
- time_idx
- price_regular
- discount_in_percent
- relative_time_idx
- volume
- log_volume
- industry_volume
- soda_volume
- avg_max_temp
- avg_volume_by_agency
- avg_volume_by_sku
